// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgyodRdUOroaa51wEW20lm0kCH-KeOnUc',
    appId: '1:33720989851:web:5c703776e8402dcd902e3e',
    messagingSenderId: '33720989851',
    projectId: 'healthsync-e8db0',
    authDomain: 'healthsync-e8db0.firebaseapp.com',
    storageBucket: 'healthsync-e8db0.appspot.com',
    measurementId: 'G-TCJJ2S1080',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAapzSZEyud-3o3IellGUIOzZ-9-BNX2OQ',
    appId: '1:33720989851:ios:774d04830ab1c50d902e3e',
    messagingSenderId: '33720989851',
    projectId: 'healthsync-e8db0',
    storageBucket: 'healthsync-e8db0.appspot.com',
    iosBundleId: 'com.example.navigationExample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAapzSZEyud-3o3IellGUIOzZ-9-BNX2OQ',
    appId: '1:33720989851:ios:280ef884d9ad8971902e3e',
    messagingSenderId: '33720989851',
    projectId: 'healthsync-e8db0',
    storageBucket: 'healthsync-e8db0.appspot.com',
    iosBundleId: 'com.example.navigationExample.RunnerTests',
  );
}
